### ISSUE TITLE
Design the ER diagram

### ISSUE THREAD

**Issue by malintha** [fontman/fontman-server#2]
The ER Diagram for following scenarios needs to be designed concretely. 

- Get the list of fonts subscribed by the user
- Get a font by font ID
- Get a list of fonts with updates
- Add a font to the registry
- Add an update to the font
- remove a font

**Comment by lpsandaruwan** [comment]
This is the ERD, I planned, But it is only for font users. :-)

![fontman-erd- 1](https://cloud.githubusercontent.com/assets/5220773/21485212/582f374a-cbc5-11e6-8587-16d44eded30c.png)

**Comment by malintha** [comment]
Thanks @lpsandaruwan. There are slight changes needs to be happened in Channel entity and subscription entity. I will upload a refurbished version and let's build on it.

**Comment by malintha** [comment]
Let's start from this. Any ideas? @pathumego @lpsandaruwan 
![erdplus-diagram](https://cloud.githubusercontent.com/assets/3253761/21486344/1dbce1f2-cbd9-11e6-8e22-28dbd8085fa8.png)

**Comment by lpsandaruwan** [comment]
This looks nice. :+1: 

@Malintha @pathumego I have these question,

1. An organisation can have both free and commercial fonts. Where to put them?
2. Fontman is not only for the users but also for font developers and designers, one should have the ability to publish their fonts using fontman. Otherwise, it will become a typical font management tool. How can we approach that?

**Comment by malintha** [comment]
We can simply tag the fonts by organization names, font families etc. So anybody can filter via the tag as they want. I think this resolves the need of having an organization table. 
If any font is free, then we can put the price as 0. Also, tag it as free.

**Comment by malintha** [comment]
Publishing of any font can also be done via this. Anybody can upload the font and the details such as author, published date, state (published, under development) can be added as meta information of the font. When we create the json payload to the frontend, we can use these key, value pairs. By this way, we dont need to worry about scalability of meta information. Have I missed anything?

**Comment by lpsandaruwan** [comment]
@Malintha cool. Problem solved. :-)

**Comment by lpsandaruwan** [comment]
This is great. I think we can now move this ERD to implementation.

**Comment by malintha** [comment]
@lpsandaruwan forgot to mention, in the tag table, primary key must be the composition of font_id and the tag. Also, lets have an auto incrementing primary key for the metadata table as well, like metadata_id to make it easy.

**Comment by lpsandaruwan** [comment]
What about having a mechanism for user ratings and comments? Just suggesting. :-)

**Comment by malintha** [comment]
@lpsandaruwan Yea, we need that. For that, lets create another table to store social information like that. :)

**Comment by pathumego** [comment]
@Malintha @lpsandaruwan we need to manage users and other user related activities and data. But shouldn't it be somewhat separate from the font services?

**Comment by pathumego** [comment]
@Malintha agree

**Comment by lpsandaruwan** [comment]
Latest ERD design, considering new UX. **Not the final version. 
![fontman server](https://cloud.githubusercontent.com/assets/5220773/21576565/ec8880ca-cf5a-11e6-8b3c-41c1da0f7679.png)

**Comment by lpsandaruwan** [comment]
ER diagram according to 2/1/17 discussion.

![fontman server](https://cloud.githubusercontent.com/assets/5220773/21601901/36788430-d1b5-11e6-9c3f-4f2e4e83aa42.png)

**Comment by lpsandaruwan** [comment]
Closing the issue, since this is the last ERD.
