### ISSUE TITLE
Implement token authentication for fontman server

### ISSUE THREAD

**Issue by malintha** [fontman/fontman-server#3]

**Comment by lpsandaruwan** [comment]
Need a clarification. :-) What happens when this token expired? Does it require the client user to log in again?

**Comment by malintha** [comment]
Yeah. This is a simplified answer for it. 
http://stackoverflow.com/questions/1592534/what-is-token-based-authentication

**Comment by lpsandaruwan** [comment]
Shall we go for a mechanism like Skype? Once user logged in, it keeps credentials until he signs out?

**Comment by lpsandaruwan** [comment]
https://github.com/fontman/fontman-server/commit/fb6be4f044dfcefde3a805442741ad552b86fc57
https://github.com/fontman/fontman-server/commit/d37da0088966a11374fa6bb69a91f0065cc3d103

Closing this since auth controller has a token-based mechanism.
