### ISSUE TITLE
Fontman package definition

### ISSUE THREAD

**Issue by pathumego** [fontman/fontman-server#5]
Since we need to define the package definition for Fontman packages with folder structure, data and files. Basically a standard distribution package font binaries, metadata file structure, fontlog structure and many other things. I suggest making a repo and maintaining a sample package to showcase and test.   `fontman/fontmanpkg`? 
When the api + standard packages we can find people to start work on packages and services for bower, npm and wordpress.

**Comment by pathumego** [comment]
@Malintha @lpsandaruwan thoughts?

**Comment by lpsandaruwan** [comment]
This is nice. It is better if we can make a standard package format ASAP.

**Comment by lpsandaruwan** [comment]
Would like to mention this, copied from Fontman old archives.

![ar](https://cloud.githubusercontent.com/assets/5220773/21505967/4314d496-cc92-11e6-8513-a827bcaf1680.png)

**Comment by pathumego** [comment]
@davelab6 any inputs before @lpsandaruwan and I start work on this.

**Comment by lpsandaruwan** [comment]
@pathumego I'm really happy with the structure [Abhaya Libre Font](https://github.com/mooniak/abhaya-libre-font) has. Additionally, we can add a metadata file, a changelog to it and a specified text file with sample markdown text for Fontman to display. Or else let's add sample text to metadata file itself.

**Comment by davelab6** [comment]
I suggest using an existing popular package format; rpm and deb are
obviously classic and have many tools, perhaps Bower or something more
github- and web-savvy is sufficient (the older formats have stuff like
epochs so you can restart the version numbering if it's getting messy...)
and maybe more familiar to the modern php/JS dev audience compared to old
school GNU devs

**Comment by lpsandaruwan** [comment]
@davelab6 Can you please clarify a little bit? :-)

**Comment by davelab6** [comment]
Well, if the structure of the Abhaya Libre Font is sufficient, the github ZIP url -  https://github.com/mooniak/abhaya-libre-font/archive/master.zip - provides a binary blob of it that you can reliably download and unpack and do what you want with. No further packaging required :)

**Comment by pathumego** [comment]
@lpsandaruwan I think looking into how we can use the api to switch between versions is also important. If we only index repos using semver.org versions we can have canonical urls to pull data to server?

**Comment by lpsandaruwan** [comment]
@pathumego Versioning won't be an issue.

I'm not sure whether I've been following the discussion clearly(outer space). :-D
Help me to clear my intentions here. :-) So there is this npm package, you can install it with 
`npm install fontman-tools`
And then you can push a record to Fontman server by doing,
`fontman push` like that?

**Comment by pathumego** [comment]
@lpsandaruwan Lets clarify this tomorrow at our meeting :)

**Comment by lpsandaruwan** [comment]
So as we discussed today, shall we use bower like config? :-)

**Comment by pathumego** [comment]
Yep, I opened a repo here to move forward on this https://github.com/fontman/fontmanpkg-spec
